api/urls.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views as rest_framework_views

from .views import EquidistantAssessmentList, EquidistantProgramViewSet, OctopusG1AssessmentList, \
    OctopusG1ProgramViewSet, TrainingProgramViewSet


app_name = 'api'

router = DefaultRouter()
router.register(r'program/equidistant', EquidistantProgramViewSet, base_name='EquidistantProgram')
router.register(r'program/octopusg1', OctopusG1ProgramViewSet, base_name='OctopusG1Program')
router.register(r'program/training', TrainingProgramViewSet, base_name='TrainingProgram')

urlpatterns = [
    path('v1/', include(router.urls)),
    path('v1/assessment/equidistant/', EquidistantAssessmentList.as_view()),
    path('v1/assessment/octopusg1/', OctopusG1AssessmentList.as_view()),
    path('v1/token/', rest_framework_views.obtain_auth_token, name='get_auth_token'),
]

clientconf/urls.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.urls import path, include
from django.views.decorators.cache import never_cache

from .views import index, EquidistantCreate, EquidistantUpdate, EquidistantDelete, OctopusCreate, OctopusUpdate, \
    OctopusDelete, TrainingCreate, TrainingUpdate, TrainingDelete


app_name = 'clientconf'

urlpatterns = [
    path('', never_cache(index), name='index'),
    path('equidistant/<int:pk>/', never_cache(EquidistantUpdate.as_view()), name='equidistant-update'),
    path('equidistant/create/', EquidistantCreate.as_view(), name='equidistant-create'),
    path('equidistant/delete/<int:pk>/', EquidistantDelete.as_view(), name='equidistant-delete'),
    path('octopus/<int:pk>/', never_cache(OctopusUpdate.as_view()), name='octopus-update'),
    path('octopus/create/', OctopusCreate.as_view(), name='octopus-create'),
    path('octopus/delete/<int:pk>/', OctopusDelete.as_view(), name='octopus-delete'),
    path('train/<int:pk>/', never_cache(TrainingUpdate.as_view()), name='training-update'),
    path('train/create/', TrainingCreate.as_view(), name='training-create'),
    path('train/delete/<int:pk>/', TrainingDelete.as_view(), name='training-delete'),
]

vfatserver/urls.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.flatpages import views as flat_views

from main.views import CustomRegistrationView, delete_account


urlpatterns = [
    path('home/', flat_views.flatpage, {'url': '/home/'}, name='home'),
    path('main/', include('main.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/register/', CustomRegistrationView.as_view(), name='register'),
    path('accounts/delete/', delete_account, name='delete'),
    path('assessment/', include('assessment.urls')),
    path('stats/', include('stats.urls')),
    path('clientconf/', include('clientconf.urls')),
    path('train/', include('train.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

clientconf/forms.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import re

from django.forms import ModelForm, TextInput, Select, CheckboxInput

from assessment.models import EquidistantSphereProgram, OctopusG1Program
from train.models import TrainingProgram


class BasicProgramForm(ModelForm):
    class Meta:
        fields = ['name', 'eye', 'thresholds', 'display_time',
                  'min_waiting_time', 'max_waiting_time',
                  'min_response_time', 'max_response_time',
                  'assessment_color', 'fixation_color', 'stimulus_size']

        widgets = {
            'name': TextInput(attrs={'class': 'w-100 form-control'}),
            'eye': Select(attrs={'class': 'w-100 form-control'}),
            'thresholds': TextInput(attrs={'class': 'w-100 form-control'}),
            'display_time': TextInput(attrs={'class': 'w-100 form-control'}),
            'min_waiting_time': TextInput(attrs={'class': 'w-100 form-control'}),
            'max_waiting_time': TextInput(attrs={'class': 'w-100 form-control'}),
            'min_response_time': TextInput(attrs={'class': 'w-100 form-control'}),
            'max_response_time': TextInput(attrs={'class': 'w-100 form-control'}),
            'assessment_color': TextInput(attrs={'class': 'w-100 form-control'}),
            'fixation_color': TextInput(attrs={'class': 'w-100 form-control'}),
            'stimulus_size': TextInput(attrs={'class': 'w-100 form-control'}),
        }

        labels = {
            'display_time': 'Stimulus display time (ms)',
            'thresholds': 'Stimulus thresholds (dB)',
            'min_waiting_time': 'Minimum waiting time (ms)',
            'max_waiting_time': 'Maximum waiting time (ms)',
            'min_response_time': 'Minimum response time (ms)',
            'max_response_time': 'Maximum response time (ms)',
            'fixation_color': 'Fixation color (RGB)',
            'assessment_color': 'Assessment color (RGB)',
            'stimulus_size': 'Stimulus size (deg)'
        }

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super(BasicProgramForm, self).__init__(*args, **kwargs)

    def clean_thresholds(self):
        data = self.cleaned_data['thresholds']
        data = re.sub('\s+', ' ', data).strip()
        return data


class BasicAssessmentProgramForm(BasicProgramForm):
    class Meta(BasicProgramForm.Meta):
        fields = BasicProgramForm.Meta.fields + ['blind_spot_tests']

        widgets = BasicProgramForm.Meta.widgets
        widgets['blind_spot_tests'] = TextInput(attrs={'class': 'w-100 form-control'})

        labels = BasicProgramForm.Meta.labels
        labels['blind_spot_tests'] = 'Blind spot tests'


class OctopusG1Form(BasicAssessmentProgramForm):
    class Meta(BasicAssessmentProgramForm.Meta):
        model = OctopusG1Program


class EquidistantForm(BasicAssessmentProgramForm):
    class Meta(BasicAssessmentProgramForm.Meta):
        model = EquidistantSphereProgram

        fields = BasicAssessmentProgramForm.Meta.fields + ['min_inclination', 'max_inclination', 'test_positions']

        widgets = BasicAssessmentProgramForm.Meta.widgets
        widgets['min_inclination'] = TextInput(attrs={'class': 'w-100 form-control'})
        widgets['max_inclination'] = TextInput(attrs={'class': 'w-100 form-control'})
        widgets['test_positions'] = TextInput(attrs={'class': 'w-100 form-control'})

        labels = BasicAssessmentProgramForm.Meta.labels
        labels['test_positions'] = 'Number of test positions'
        labels['min_inclination'] = 'Minimum inclination (deg)'
        labels['max_inclination'] = 'Maximum inclination (deg)'


class TrainingForm(BasicProgramForm):
    class Meta(BasicProgramForm.Meta):
        model = TrainingProgram

        fields = BasicProgramForm.Meta.fields + ['training_positions', 'random_training_color', 'reinforcement']

        widgets = BasicProgramForm.Meta.widgets
        widgets['training_positions'] = TextInput(attrs={'class': 'w-100 form-control'})
        widgets['random_training_color'] = CheckboxInput(attrs={'class': 'form-control'})
        widgets['reinforcement'] = CheckboxInput(attrs={'class': 'form-control'})

        labels = BasicProgramForm.Meta.labels
        labels['training_positions'] = 'Number of training positions'
        labels['random_training_color'] = 'Random training color'
        labels['assessment_color'] = 'Training color (RGB)'
        labels['reinforcement'] = 'Reinforcement learning'

clientconf/views.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.shortcuts import render
from django.http import Http404
from django.db import models

from .forms import EquidistantForm, OctopusG1Form, TrainingForm
from assessment.models import EquidistantSphereProgram, OctopusG1Program
from train.models import TrainingProgram


###
# Common list view
###

def index(request):
    equidistant_list = EquidistantSphereProgram.objects.filter(user=request.user).order_by('name')
    octopus_list = OctopusG1Program.objects.filter(user=request.user).order_by('name')
    training_list = TrainingProgram.objects.filter(user=request.user).order_by('name')

    context = {'equidistant_list': equidistant_list, 'octopus_list': octopus_list,
               'training_list': training_list}

    return render(request, 'clientconf/index.html', context)


###
# Base classes
###

class AbstractProgramCreate(CreateView):
    success_url = reverse_lazy('clientconf:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_initial(self):
        return {'eye': 0,
                'thresholds': '0 10 15 20',
                'display_time': 200,
                'min_waiting_time': 1000,
                'max_waiting_time': 3000,
                'min_response_time': 300,
                'max_response_time': 750,
                'assessment_color': 'FFFFFF',
                'fixation_color': '0000FF',
                'stimulus_size': 0.43,
                }

    def get_context_data(self, **kwargs):
        context = super(AbstractProgramCreate, self).get_context_data(**kwargs)
        context['cancel_url'] = reverse('clientconf:index')
        return context


class AbstractAssessmentProgramCreate(AbstractProgramCreate):
    def get_initial(self):
        initials = super(AbstractAssessmentProgramCreate, self).get_initial()
        initials['blind_spot_tests'] = 3
        return initials


class AbstractProgramUpdate(UpdateView):
    success_url = reverse_lazy('clientconf:index')

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(AbstractProgramUpdate, self).get_context_data(**kwargs)
        context['cancel_url'] = reverse('clientconf:index')

        return context


class AbstractProgramDelete(DeleteView):
    success_url = reverse_lazy('clientconf:index')
    template_name = 'clientconf/program_delete.html'

    def get_object(self, queryset=None):
        obj = super(AbstractProgramDelete, self).get_object()
        if not obj.user == self.request.user:
            raise Http404

        return obj

    def delete(self, request, *args, **kwargs):
        try:
            return super(AbstractProgramDelete, self).delete(request, *args, **kwargs)
        except models.ProtectedError as e:
            return render(request, self.template_name, context={
                'object': self.get_object(),
                'message': 'This program cannot be deleted because there are assessments linked to it.'})


###
# Equidistant Program
###

class EquidistantCreate(AbstractAssessmentProgramCreate):
    form_class = EquidistantForm
    template_name = 'clientconf/equidistant_create.html'

    def get_initial(self):
        initials = super(EquidistantCreate, self).get_initial()
        initials['name'] = 'Left Eye (100 Positions)'
        initials['test_positions'] = 100
        initials['min_inclination'] = 3
        initials['max_inclination'] = 30
        return initials


class EquidistantUpdate(AbstractProgramUpdate):
    form_class = EquidistantForm
    model = EquidistantSphereProgram
    template_name = 'clientconf/equidistant_update.html'

    def get_context_data(self, **kwargs):
        context = super(EquidistantUpdate, self).get_context_data(**kwargs)
        context['delete_url'] = reverse('clientconf:equidistant-delete',
                                        args=[self.kwargs['pk']])
        return context


class EquidistantDelete(AbstractProgramDelete):
    model = EquidistantSphereProgram


###
# Octopus Program
###

class OctopusCreate(AbstractAssessmentProgramCreate):
    form_class = OctopusG1Form
    template_name = 'clientconf/octopus_create.html'

    def get_initial(self):
        initials = super(OctopusCreate, self).get_initial()
        initials['name'] = 'Left Eye'
        # Calibrated for iPhone 6 to match Octopus 900
        initials['thresholds'] = '20.83333333 19.99 19.34 18.56363636 17.70714286 16.83684211 15.98461538 15.19230769 14.4 13.56097561 12.64814815 11.76119403 10.84782609 9.96460177 9.05309735 8.14482759 7.31730769 6.46153846 5.5483871 4.63414634 3.69811321 2.78461538 1.8313253'
        return initials


class OctopusUpdate(AbstractProgramUpdate):
    form_class = OctopusG1Form
    model = OctopusG1Program
    template_name = 'clientconf/octopus_update.html'

    def get_context_data(self, **kwargs):
        context = super(OctopusUpdate, self).get_context_data(**kwargs)
        context['delete_url'] = reverse('clientconf:octopus-delete',
                                        args=[self.kwargs['pk']])
        return context


class OctopusDelete(AbstractProgramDelete):
    model = OctopusG1Program


###
# Training Program
###


class TrainingCreate(AbstractProgramCreate):
    form_class = TrainingForm
    template_name = 'clientconf/training_create.html'

    def get_initial(self):
        initials = super(TrainingCreate, self).get_initial()
        initials['name'] = 'Train Left'
        initials['thresholds'] = '28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0'
        initials['training_positions'] = 100
        initials['random_training_color'] = True
        initials['reinforcement'] = True
        return initials


class TrainingUpdate(AbstractProgramUpdate):
    form_class = TrainingForm
    model = TrainingProgram
    template_name = 'clientconf/training_update.html'

    def get_context_data(self, **kwargs):
        context = super(TrainingUpdate, self).get_context_data(**kwargs)
        context['delete_url'] = reverse('clientconf:training-delete',
                                        args=[self.kwargs['pk']])

        return context


class TrainingDelete(AbstractProgramDelete):
    model = TrainingProgram

clientconf/templates/clientconf/equidistant_create.html
<!--
Copyright 2019 Matthias Ring
Machine Learning and Data Analytics Lab
Friedrich-Alexander-University Erlangen-Nuremberg

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->


{% extends 'base.html' %}

{% block content %}

<h3 class="pb-3">New Equidistant Program</h3>

{% include 'clientconf/equidistant_form.html' with submit_label='Create' cancel_label='Cancel' cancel_href=cancel_url %}

{% endblock %}

clientconf/templates/clientconf/equidistant_form.html
<!--
Copyright 2019 Matthias Ring
Machine Learning and Data Analytics Lab
Friedrich-Alexander-University Erlangen-Nuremberg

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->


<form action="" method="post">
    {% csrf_token %}

    <div class="form-row">
        <div class="col-md-4 col-lg-3 col-form-label">
            {{form.name.label_tag}}
        </div>
        <div class="col-md-5 col-lg-7">
            {{ form.name }}
        </div>
        <div class="col-md-1 col-lg-1 col-form-label">
            {{form.eye.label_tag}}
        </div>
        <div class="col-md-2 col-lg-1">
            {{ form.eye }}
        </div>
    </div>

    {% if form.name.errors or form.eye.errors %}
    <div class="alert alert-danger" role="alert">
        {{form.name.errors}}
        {{form.eye.errors}}
    </div>
    {% endif %}

    <div class="form-row">
        <div class="col-md-4 col-lg-3 col-form-label">
            {{form.thresholds.label_tag}}
        </div>
        <div class="col-md-8 col-lg-9">
            {{ form.thresholds }}
        </div>
    </div>

    {% if form.thresholds.errors %}
    <div class="alert alert-danger" role="alert">
        {{form.thresholds.errors}}
    </div>
    {% endif %}

    <div class="form-row">
        <div class="col-md-4 col-lg-3 col-form-label">
            {{form.test_positions.label_tag}}
        </div>
        <div class="col-md-2 col-lg-3">
            {{ form.test_positions }}
        </div>
        <div class="col-md-4 col-lg-3 col-form-label">
            {{form.blind_spot_tests.label_tag}}
        </div>
        <div class="col-md-2 col-lg-3">
            {{ form.blind_spot_tests }}
        </div>
    </div>

    {% if form.test_positions.errors or form.blind_spot_tests.errors %}
    <div class="alert alert-danger" role="alert">
        {{form.blind_spot_tests.errors}}
        {{form.test_positions.errors}}
    </div>
    {% endif %}

    <div class="form-row">
        <div class="col-md-4 col-lg-3 col-form-label">
            {{form.display_time.label_tag}}
        </div>
        <div class="col-md-2 col-lg-3">
            {{ form.display_time }}
        </div>
        <div class="col-md-4 col-lg-3 col-form-label">
            {{form.stimulus_size.label_tag}}
        </div>
        <div class="col-md-2 col-lg-3">
            {{ form.stimulus_size }}
        </div>
    </div>

    {% if form.display_time.errors or form.stimulus_size.errors %}
    <div class="alert alert-danger" role="alert">
        {{form.display_time.errors}}
        {{form.stimulus_size.errors}}
    </div>
    {% endif %}

    <div class="form-row">
        <div class="col-md-4 col-lg-3 col-form-label">
            {{form.min_waiting_time.label_tag}}
        </div>
        <div class="col-md-2 col-lg-3">
            {{ form.min_waiting_time }}
        </div>
        <div class="col-md-4 col-lg-3 col-form-label">
            {{form.max_waiting_time.label_tag}}
        </div>
        <div class="col-md-2 col-lg-3">
            {{ form.max_waiting_time }}
        </div>
    </div>

    {% if form.min_waiting_time.errors or form.max_waiting_time.errors %}
    <div class="alert alert-danger" role="alert">
        {{form.min_waiting_time.errors}}
        {{form.max_waiting_time.errors}}
    </div>
    {% endif %}

    <div class="form-row">
        <div class="col-md-4 col-lg-3 col-form-label">
            {{form.min_response_time.label_tag}}
        </div>
        <div class="col-md-2 col-lg-3">
            {{ form.min_response_time }}
        </div>
        <div class="col-md-4 col-lg-3 col-form-label">
            {{form.max_response_time.label_tag}}
        </div>
        <div class="col-md-2 col-lg-3">
            {{ form.max_response_time }}
        </div>
    </div>

    {% if form.min_response_time.errors or form.max_response_time.errors %}
    <div class="alert alert-danger" role="alert">
        {{form.min_response_time.errors}}
        {{form.max_response_time.errors}}
    </div>
    {% endif %}

    <div class="form-row">
        <div class="col-md-4 col-lg-3 col-form-label">
            {{form.min_inclination.label_tag}}
        </div>
        <div class="col-md-2 col-lg-3">
            {{ form.min_inclination }}
        </div>
        <div class="col-md-4 col-lg-3 col-form-label">
            {{form.max_inclination.label_tag}}
        </div>
        <div class="col-md-2 col-lg-3">
            {{ form.max_inclination }}
        </div>
    </div>

    {% if form.min_inclination.errors or form.max_inclination.errors %}
    <div class="alert alert-danger" role="alert">
        {{form.min_inclination.errors}}
        {{form.max_inclination.errors}}
    </div>
    {% endif %}

    <div class="form-row">
        <div class="col-md-4 col-lg-3 col-form-label">
            {{form.assessment_color.label_tag}}
        </div>
        <div class="col-md-2 col-lg-3">
            {{ form.assessment_color }}
        </div>
        <div class="col-md-4 col-lg-3 col-form-label">
            {{form.fixation_color.label_tag}}
        </div>
        <div class="col-md-2 col-lg-3">
            {{ form.fixation_color }}
        </div>
    </div>

    {% if form.assessment_color.errors or form.fixation_color.errors %}
    <div class="alert alert-danger" role="alert">
        {{form.assessment_color.errors}}
        {{form.fixation_color.errors}}
    </div>
    {% endif %}

    <div class="form-row py-3">
        {% if submit_label %}
        <div class="px-1">
            <input class="btn btn-primary" type="submit" value="{{submit_label}}"/>
        </div>
        {% endif %}

        {% if cancel_label %}
        <div class="px-1">
            <a href="{{cancel_href}}" class="btn btn-info">{{cancel_label}}</a>
        </div>
        {% endif %}

        {% if delete_label %}
        <div class="px-1">
            <a href="{{delete_href}}" class="btn btn-danger">{{delete_label}}</a>
        </div>
        {% endif %}
    </div>
</form>

clientconf/templates/clientconf/equidistant_update.html
<!--
Copyright 2019 Matthias Ring
Machine Learning and Data Analytics Lab
Friedrich-Alexander-University Erlangen-Nuremberg

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->


{% extends 'base.html' %}

{% block content %}

<h3 class="pb-3">Edit Equidistant Program</h3>

{% include 'clientconf/equidistant_form.html' with submit_label='Update' cancel_label='Cancel' cancel_href=cancel_url delete_label='Delete' delete_href=delete_url%}

{% endblock %}

clientconf/templates/clientconf/index.html
<!--
Copyright 2019 Matthias Ring
Machine Learning and Data Analytics Lab
Friedrich-Alexander-University Erlangen-Nuremberg

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->


{% extends 'base.html' %}

{% block content %}

<h3>App Settings</h3>

<h4 class="pt-3">Equidistant Programs</h4>

{% if equidistant_list %}
<ul style="list-style-type:none;margin:0;padding:0;">
    {% for program in equidistant_list %}
    <li>
        <a href="{% url 'clientconf:equidistant-update' program.id %}">
            {{ program.name }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endif %}

<a href="{% url 'clientconf:equidistant-create' %}" class="btn btn-primary btn-inline mt-2">
    <i class="fas fa-plus"></i> Add
</a>

<h4 class="pt-3">Octopus G1-Based Programs</h4>

{% if octopus_list %}
<ul style="list-style-type:none;margin:0;padding:0;">
    {% for program in octopus_list %}
    <li>
        <a href="{% url 'clientconf:octopus-update' program.id %}">
            {{ program.name }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endif %}

<a href="{% url 'clientconf:octopus-create' %}" class="btn btn-primary btn-inline mt-2">
    <i class="fas fa-plus"></i> Add
</a>


<h4 class="pt-3">Training Programs</h4>

{% if training_list %}
<ul style="list-style-type:none;margin:0;padding:0;">
    {% for program in training_list %}
    <li>
        <a href="{% url 'clientconf:training-update' program.id %}">
            {{ program.name }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endif %}

<a href="{% url 'clientconf:training-create' %}" class="btn btn-primary btn-inline mt-2">
    <i class="fas fa-plus"></i> Add
</a>

{% endblock %}

clientconf/templates/clientconf/octopus_create.html
<!--
Copyright 2019 Matthias Ring
Machine Learning and Data Analytics Lab
Friedrich-Alexander-University Erlangen-Nuremberg

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->


{% extends 'base.html' %}

{% block content %}

<h3 class="pb-3">New Octopus G1-Based Program</h3>

{% include 'clientconf/octopus_form.html' with submit_label='Create' cancel_label='Cancel' cancel_href=cancel_url %}

{% endblock %}