api/urls.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views as rest_framework_views

from .views import EquidistantAssessmentList, EquidistantProgramViewSet, OctopusG1AssessmentList, \
    OctopusG1ProgramViewSet, TrainingProgramViewSet


app_name = 'api'

router = DefaultRouter()
router.register(r'program/equidistant', EquidistantProgramViewSet, base_name='EquidistantProgram')
router.register(r'program/octopusg1', OctopusG1ProgramViewSet, base_name='OctopusG1Program')
router.register(r'program/training', TrainingProgramViewSet, base_name='TrainingProgram')

urlpatterns = [
    path('v1/', include(router.urls)),
    path('v1/assessment/equidistant/', EquidistantAssessmentList.as_view()),
    path('v1/assessment/octopusg1/', OctopusG1AssessmentList.as_view()),
    path('v1/token/', rest_framework_views.obtain_auth_token, name='get_auth_token'),
]

assessment/urls.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.urls import path
from django.views.decorators.cache import never_cache

from . import views

app_name = 'assessment'

urlpatterns = [
    path('', never_cache(views.index), name='index'),
    path('equidistant/<int:assessment_id>/', views.detail_equidistant, name='detail-equidistant'),
    path('equidistant/<int:assessment_id>/field', views.detail_equidistant_field, name='detail-equidistant-field'),
    path('equidistant/<int:assessment_id>/curve', views.detail_equidistant_curve, name='detail-equidistant-curve'),
    path('equidistant/delete/<int:assessment_id>/', views.delete_equidistant, name='delete-equidistant'),
    path('octopusg1/<int:assessment_id>/', views.detail_octopusg1, name='detail-octopusg1'),
    path('octopusg1/<int:assessment_id>/field', views.detail_octopusg1_field, name='detail-octopusg1-field'),
    path('octopusg1/<int:assessment_id>/curve', views.detail_octopusg1_curve, name='detail-octopusg1-curve'),
    path('octopusg1/delete/<int:assessment_id>/', views.delete_octopusg1, name='delete-octopusg1'),
]

vfatserver/urls.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.flatpages import views as flat_views

from main.views import CustomRegistrationView, delete_account


urlpatterns = [
    path('home/', flat_views.flatpage, {'url': '/home/'}, name='home'),
    path('main/', include('main.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/register/', CustomRegistrationView.as_view(), name='register'),
    path('accounts/delete/', delete_account, name='delete'),
    path('assessment/', include('assessment.urls')),
    path('stats/', include('stats.urls')),
    path('clientconf/', include('clientconf.urls')),
    path('train/', include('train.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

assessment/models.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.db import models
from django.db.models.signals import pre_delete, pre_save
from django.dispatch.dispatcher import receiver
from django.core.validators import RegexValidator
from django.conf import settings

from datetime import datetime

from main.models import User

EYE_CHOICES = ((0, 'Left'), (1, 'Right'),)

decimal_separator = r'\.' if settings.DECIMAL_SEPARATOR == '.' else r','
float_list_validator = RegexValidator(r'^(\d+(' + decimal_separator + r')?\d* *)+$',
                                      'Please provide a white space separated list of numbers')


###
# Programs
###

class BasicProgram(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    fixation_color = models.CharField(max_length=7)
    assessment_color = models.CharField(max_length=7)
    eye = models.IntegerField(choices=EYE_CHOICES)
    max_waiting_time = models.FloatField()
    min_waiting_time = models.FloatField()
    max_response_time = models.FloatField()
    min_response_time = models.FloatField()
    display_time = models.FloatField()
    stimulus_size = models.FloatField()
    thresholds = models.CharField(max_length=512, validators=[float_list_validator])

    class Meta:
        abstract = True


class BasicAssessmentProgram(BasicProgram):
    blind_spot_tests = models.PositiveIntegerField()

    class Meta:
        abstract = True


class EquidistantSphereProgram(BasicAssessmentProgram):
    test_positions = models.IntegerField()
    max_inclination = models.FloatField()
    min_inclination = models.FloatField()


class OctopusG1Program(BasicAssessmentProgram):
    pass


###
# Assessments
###


def user_directory_path(instance, filename):
    return 'assessment/{}/{}'.format(instance.user.id, datetime.now())


class Assessment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.FileField(upload_to=user_directory_path)
    date = models.DateTimeField(auto_now_add=True)
    duration = models.DurationField()
    tested_eye = models.IntegerField(choices=EYE_CHOICES)
    false_positive = models.PositiveIntegerField()
    blind_spot_false_positive = models.PositiveIntegerField()

    # save these configuration settings in case configuration gets updated after assessment
    blind_spot_tests = models.PositiveIntegerField()
    thresholds = models.CharField(max_length=512, validators=[float_list_validator])
    max_response_time = models.FloatField()
    min_response_time = models.FloatField()

    class Meta:
        abstract = True


class EquidistantAssessment(Assessment):
    configuration = models.ForeignKey(EquidistantSphereProgram, on_delete=models.PROTECT)


@receiver(pre_delete, sender=EquidistantAssessment)
def delete_equidistant_file(sender, instance, *args, **kwargs):
    instance.file.delete()


@receiver(pre_save, sender=EquidistantAssessment)
def equidistant_pre_save(sender, instance, *args, **kwargs):
    instance.thresholds = instance.configuration.thresholds
    instance.blind_spot_tests = instance.configuration.blind_spot_tests
    instance.min_response_time = instance.configuration.min_response_time
    instance.max_response_time = instance.configuration.max_response_time


pre_delete.connect(delete_equidistant_file, sender=EquidistantAssessment)
pre_save.connect(equidistant_pre_save, sender=EquidistantAssessment)


class OctopusG1Assessment(Assessment):
    configuration = models.ForeignKey(OctopusG1Program, on_delete=models.PROTECT)


@receiver(pre_delete, sender=OctopusG1Assessment)
def delete_octopusg1_file(sender, instance, *args, **kwargs):
    instance.file.delete()


@receiver(pre_save, sender=OctopusG1Assessment)
def octopusg1_pre_save(sender, instance, *args, **kwargs):
    instance.thresholds = instance.configuration.thresholds
    instance.blind_spot_tests = instance.configuration.blind_spot_tests
    instance.min_response_time = instance.configuration.min_response_time
    instance.max_response_time = instance.configuration.max_response_time


pre_delete.connect(delete_octopusg1_file, sender=OctopusG1Assessment)
pre_save.connect(octopusg1_pre_save, sender=OctopusG1Assessment)

assessment/views.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import matplotlib as mpl
mpl.use('Agg')

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

import vfatserver.consts as consts
import vfatserver.util as util
from .util import plot_visual_field, plot_curve
from .models import EquidistantAssessment, OctopusG1Assessment


def index(request):
    equidistant_left = EquidistantAssessment.objects.filter(user=request.user, tested_eye=0).order_by('-date')
    equidistant_right = EquidistantAssessment.objects.filter(user=request.user, tested_eye=1).order_by('-date')

    octopusg1_left = OctopusG1Assessment.objects.filter(user=request.user, tested_eye=0).order_by('-date')
    octopusg1_right = OctopusG1Assessment.objects.filter(user=request.user, tested_eye=1).order_by('-date')

    context = {'equidistant_left': equidistant_left, 'equidistant_right': equidistant_right,
               'octopusg1_left': octopusg1_left, 'octopusg1_right': octopusg1_right}

    return render(request, 'assessment/index.html', context)


def detail_equidistant(request, assessment_id):
    equidistant_assessment = get_object_or_404(EquidistantAssessment, pk=assessment_id, user=request.user)


    context = {'assessment': equidistant_assessment,
               'program_url': reverse('clientconf:equidistant-update', args=[equidistant_assessment.configuration.id]),
               'field_url': reverse('assessment:detail-equidistant-field', args=[equidistant_assessment.id]),
               'curve_url': reverse('assessment:detail-equidistant-curve', args=[equidistant_assessment.id]),
               'delete_url': reverse('assessment:delete-equidistant', args=[equidistant_assessment.id])}

    return render(request, 'assessment/detail.html', context)


def detail_octopusg1(request, assessment_id):
    ocotopus_assessment = get_object_or_404(OctopusG1Assessment, pk=assessment_id, user=request.user)


    context = {'assessment': ocotopus_assessment,
               'program_url': reverse('clientconf:octopus-update', args=[ocotopus_assessment.configuration.id]),
               'field_url': reverse('assessment:detail-octopusg1-field', args=[ocotopus_assessment.id]),
               'curve_url': reverse('assessment:detail-octopusg1-curve', args=[ocotopus_assessment.id]),
               'delete_url': reverse('assessment:delete-octopusg1', args=[ocotopus_assessment.id])}

    return render(request, 'assessment/detail.html', context)


def detail_equidistant_field(request, assessment_id):
    assessment = get_object_or_404(EquidistantAssessment, pk=assessment_id, user=request.user)

    fig = plot_visual_field(assessment)

    return util.fig_to_svg_response(fig)


def detail_octopusg1_field(request, assessment_id):
    assessment = get_object_or_404(OctopusG1Assessment, pk=assessment_id, user=request.user)

    fig = plot_visual_field(assessment)

    return util.fig_to_svg_response(fig)


def detail_equidistant_curve(request, assessment_id):
    assessment = get_object_or_404(EquidistantAssessment, pk=assessment_id, user=request.user)

    fig = plot_curve(assessment)

    return util.fig_to_svg_response(fig)


def detail_octopusg1_curve(request, assessment_id):
    assessment = get_object_or_404(OctopusG1Assessment, pk=assessment_id, user=request.user)

    fig = plot_curve(assessment)

    return util.fig_to_svg_response(fig)


def delete_equidistant(request, assessment_id):
    assessment = get_object_or_404(EquidistantAssessment, user=request.user, pk=assessment_id)

    if request.method == 'POST':
        if request.user.username != consts.demo_user_name:
            assessment.delete()
            return redirect('assessment:index')
        else:
            return render(request, 'assessment/delete.html',
                          context={'assessment': assessment,
                                   'back_url': reverse('assessment:detail-equidistant', args=[assessment.id]),
                                   'message': 'Demo assessments cannot be deleted!'})
    else:
        return render(request, 'assessment/delete.html',
                      context={'assessment': assessment,
                               'back_url': reverse('assessment:detail-equidistant', args=[assessment.id])})


def delete_octopusg1(request, assessment_id):
    assessment = get_object_or_404(OctopusG1Assessment, user=request.user, pk=assessment_id)

    if request.method == 'POST':
        if request.user.username != consts.demo_user_name:
            assessment.delete()
            return redirect('assessment:index')
        else:
            return render(request, 'assessment/delete.html',
                          context={'assessment': assessment,
                                   'back_url': reverse('assessment:detail-octopusg1', args=[assessment.id]),
                                   'message': 'Demo assessments cannot be deleted!'})
    else:
        return render(request, 'assessment/delete.html',
                      context={'assessment': assessment,
                               'back_url': reverse('assessment:detail-octopusg1', args=[assessment.id])})

assessment/templates/assessment/delete.html
<!--
Copyright 2019 Matthias Ring
Machine Learning and Data Analytics Lab
Friedrich-Alexander-University Erlangen-Nuremberg

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->


{% extends 'base.html' %}

{% block content %}

{% if message %}
<div class="alert alert-danger" role="alert">
    {{ message}}
</div>
{% endif %}

<h3 class="pb-3">Delete Assessment</h3>

<form action="" method="post">
    {% csrf_token %}
    <p>Please confirm to delete this assessment from {{ assessment.date|date:"Y-m-d, l, H:i" }}.</p>

    <div class="form-row">
        <div class="px-1">
            <input class="btn btn-danger" type="submit" value="Confirm"/>
        </div>
        <div class="px-1">
            <a href="{{back_url}}" class="btn btn-info">Cancel</a>
        </div>
    </div>
</form>

{% endblock %}

assessment/templates/assessment/detail.html
<!--
Copyright 2019 Matthias Ring
Machine Learning and Data Analytics Lab
Friedrich-Alexander-University Erlangen-Nuremberg

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

{% extends 'base.html' %}

{% block header %}
{% include 'scripts.html' %}
{% endblock %}

{% block content %}

<h3 class="pb-3">Visual Field Assessment</h3>

<div class="container">
    <div class="row">
        <div class="table-responsive">
            <table class="table table-bordered" style="white-space: nowrap; width:1%;">
                <thead>
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Time</th>
                    <th scope="col">Program</th>
                    <th scope="col">Eye</th>
                    <th scope="col">Duration</th>
                    <th scope="col">False Positives</th>
                    <th scope="col">Blind Spot False Positives</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                <tr class="">
                    <td class="align-middle">{{ assessment.date|date:"Y-m-d" }}</td>
                    <td class="align-middle">{{ assessment.date|date:"H:i" }}</td>
                    <td class="align-middle"><a href="{{program_url}}">{{ assessment.configuration.name }}</a></td>
                    <td class="align-middle">{{ assessment.get_tested_eye_display }}</td>
                    <td class="align-middle">{{ assessment.duration }}</td>
                    <td class="align-middle">{{ assessment.false_positive }}</td>
                    <td class="align-middle">{{ assessment.blind_spot_false_positive }} / {{assessment.blind_spot_tests}}
                    </td>
                    <td class="align-middle"><a href="{{delete_url}}" class="btn btn-danger">Delete</a></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 py-3">
            <div class="mx-auto">
                <h5>Visual Field</h5>
                <div id="loading_message_1">
                    <p style="font-size:x-small">Loading image...</p>
                </div>
                <img onload="imageLoaded('loading_message_1');" class="img-fluid" src="{{field_url}}"/>
            </div>
        </div>
        <div class="col-lg-6 py-3">
            <div class="mx-auto">
                <h5>Defect Curve</h5>
                <div id="loading_message_2">
                    <p style="font-size:x-small">Loading image...</p>
                </div>

                <img onload="imageLoaded('loading_message_2');" class="img-fluid" src="{{curve_url}}"/>
            </div>
        </div>
    </div>
</div>

{% endblock %}

assessment/templates/assessment/index.html
<!--
Copyright 2019 Matthias Ring
Machine Learning and Data Analytics Lab
Friedrich-Alexander-University Erlangen-Nuremberg

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->


{% extends 'base.html' %}

{% block content %}

<h3 class="pb-3">Your Assessments</h3>

{% if not equidistant_left and not equidistant_right and not octopusg1_left and not octopusg1_right %}

<div class="alert alert-info" role="alert">
    No assessments available.
</div>

{% else %}

{% if equidistant_left or equidistant_right %}

<h4 class="pb-3">Equidistant Assessments</h4>

<div class="row">
    {% include 'assessment/index_partial_list.html' with title='Left Eye' list=equidistant_left detail_url='assessment:detail-equidistant' %}
    {% include 'assessment/index_partial_list.html' with title='Right Eye' list=equidistant_right detail_url='assessment:detail-equidistant' %}
</div>
{% endif %}

{% if octopusg1_left or octopusg1_right %}

<h4 class="py-3">Octopus G1-Based Assessments</h4>

<div class="row">
    {% include 'assessment/index_partial_list.html' with title='Left Eye' list=octopusg1_left detail_url='assessment:detail-octopusg1'  %}
    {% include 'assessment/index_partial_list.html' with title='Right Eye' list=octopusg1_right detail_url='assessment:detail-octopusg1'  %}
</div>

{% endif %}

{% endif %}

{% endblock %}

assessment/templates/assessment/index_partial_list.html
<!--
Copyright 2019 Matthias Ring
Machine Learning and Data Analytics Lab
Friedrich-Alexander-University Erlangen-Nuremberg

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->


<div class="col-sm-6">
    <h5 class="py-1">{{title}}</h5>

    {% if list %}
    <ul style="list-style-type:none;margin:0;padding:0;">
        {% for assessment in list %}
        <li>
            <a href="{% url detail_url assessment.id %}">
                {{ assessment.date|date:"Y-m-d, l, H:i" }}
            </a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <div class="alert alert-info" role="alert">
        No assessments available.
    </div>
    {% endif %}
</div>