api/urls.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views as rest_framework_views

from .views import EquidistantAssessmentList, EquidistantProgramViewSet, OctopusG1AssessmentList, \
    OctopusG1ProgramViewSet, TrainingProgramViewSet


app_name = 'api'

router = DefaultRouter()
router.register(r'program/equidistant', EquidistantProgramViewSet, base_name='EquidistantProgram')
router.register(r'program/octopusg1', OctopusG1ProgramViewSet, base_name='OctopusG1Program')
router.register(r'program/training', TrainingProgramViewSet, base_name='TrainingProgram')

urlpatterns = [
    path('v1/', include(router.urls)),
    path('v1/assessment/equidistant/', EquidistantAssessmentList.as_view()),
    path('v1/assessment/octopusg1/', OctopusG1AssessmentList.as_view()),
    path('v1/token/', rest_framework_views.obtain_auth_token, name='get_auth_token'),
]

assessment/urls.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.urls import path
from django.views.decorators.cache import never_cache

from . import views

app_name = 'assessment'

urlpatterns = [
    path('', never_cache(views.index), name='index'),
    path('equidistant/<int:assessment_id>/', views.detail_equidistant, name='detail-equidistant'),
    path('equidistant/<int:assessment_id>/field', views.detail_equidistant_field, name='detail-equidistant-field'),
    path('equidistant/<int:assessment_id>/curve', views.detail_equidistant_curve, name='detail-equidistant-curve'),
    path('equidistant/delete/<int:assessment_id>/', views.delete_equidistant, name='delete-equidistant'),
    path('octopusg1/<int:assessment_id>/', views.detail_octopusg1, name='detail-octopusg1'),
    path('octopusg1/<int:assessment_id>/field', views.detail_octopusg1_field, name='detail-octopusg1-field'),
    path('octopusg1/<int:assessment_id>/curve', views.detail_octopusg1_curve, name='detail-octopusg1-curve'),
    path('octopusg1/delete/<int:assessment_id>/', views.delete_octopusg1, name='delete-octopusg1'),
]

stats/urls.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.urls import path

from . import views


app_name = 'stats'

urlpatterns = [
    path('', views.index, name='index'),
]

vfatserver/urls.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.flatpages import views as flat_views

from main.views import CustomRegistrationView, delete_account


urlpatterns = [
    path('home/', flat_views.flatpage, {'url': '/home/'}, name='home'),
    path('main/', include('main.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/register/', CustomRegistrationView.as_view(), name='register'),
    path('accounts/delete/', delete_account, name='delete'),
    path('assessment/', include('assessment.urls')),
    path('stats/', include('stats.urls')),
    path('clientconf/', include('clientconf.urls')),
    path('train/', include('train.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

stats/models.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.db import models

stats/views.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.shortcuts import render

from assessment.models import EquidistantAssessment, OctopusG1Assessment


def index(request):
    context = {'program_type': None}
    program_type = request.GET.get('program_type', 'equidistant')

    if program_type == 'equidistant':
        assessments_left = EquidistantAssessment.objects.filter(user=request.user, tested_eye=0) \
                               .order_by('date').reverse()[:3]
        assessments_right = EquidistantAssessment.objects.filter(user=request.user, tested_eye=1) \
                                .order_by('date').reverse()[:3]

        context = {'left': assessments_left, 'right': assessments_right, 'program_type': program_type}

    elif program_type == 'octopusg1':
        assessments_left = OctopusG1Assessment.objects.filter(user=request.user, tested_eye=0) \
                               .order_by('date').reverse()[:3]
        assessments_right = OctopusG1Assessment.objects.filter(user=request.user, tested_eye=1) \
                                .order_by('date').reverse()[:3]

        context = {'left': assessments_left, 'right': assessments_right, 'program_type': program_type}

    return render(request, 'stats/index.html', context)

stats/templates/stats/index.html
<!--
Copyright 2019 Matthias Ring
Machine Learning and Data Analytics Lab
Friedrich-Alexander-University Erlangen-Nuremberg

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->


{% extends 'base.html' %}

{% block header %}

<style>

.carousel-control-next-icon {
    background-image : url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%343A40' viewBox='0 0 8 8'%3E%3Cpath d='M1.5 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E") !important;
}
.carousel-control-prev-icon {
    background-image : url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%343A40' viewBox='0 0 8 8'%3E%3Cpath d='M4 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E") !important;
}
.carousel-caption {
    color: black;
    position: absolute;
    left: auto;
    top: auto;
    right: 0;
    bottom: 0;
}



</style>

{% endblock %}

{% block content %}

<h3 class="pb-3">Progression of Your Visual Field</h3>

<form method="get">
    <fieldset class="form-group pb-3">
        <div class="form-check">
            <label class="form-check-label">
                {% if program_type == "equidistant" %}
                <input onchange='this.form.submit();' type="radio" class="form-check-input" name="program_type"
                       id="optionsRadios1" value="equidistant" checked>
                {% else %}
                <input onchange='this.form.submit();' type="radio" class="form-check-input" name="program_type"
                       id="optionsRadios1" value="equidistant">
                {% endif %}
                Equidistant Assessments
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                {% if program_type == "octopusg1" %}
                <input onchange='this.form.submit();' type="radio" class="form-check-input" name="program_type"
                       id="optionsRadios2" value="octopusg1" checked>
                {% else %}
                <input onchange='this.form.submit();' type="radio" class="form-check-input" name="program_type"
                       id="optionsRadios2" value="octopusg1">
                {% endif %}
                Octopus G1-Based Assessments
            </label>
        </div>
    </fieldset>
</form>

{% if not left and not right %}
<div class="alert alert-info" role="alert">
    No assessments available.
</div>
{% else %}

<h4 class="pb-3">Left Eye</h4>

{% if left %}
<p>Slide show of the three most recent assessments</p>

<div id="carouselLeft" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        {% for assessment in left %}
        <div class="carousel-item {% if forloop.counter0 == 0 %}active{%endif%}" align="center">
            {% if program_type == "octopusg1" %}
            <img class="d-block img-fluid" src="{% url 'assessment:detail-octopusg1-field' assessment.id %}"/>
            {% elif program_type == "equidistant" %}
            <img class="d-block img-fluid" src="{% url 'assessment:detail-equidistant-field' assessment.id %}"/>
            {% endif %}
            <div class="carousel-caption text-right">
                {{assessment.date|date:"Y-m-d"}}<br/>
                {{assessment.date|date:"H:i"}}
            </div>
        </div>
        {% endfor %}
    </div>
    {% if left|length > 1 %}
    <a class="carousel-control-prev" href="#carouselLeft" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselLeft" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    {% endif %}
</div>

{% else %}
<div class="alert alert-info" role="alert">
    No assessments available.
</div>
{% endif %}

<h4 class="py-3">Right Eye</h4>

{% if right %}
<p>Slide show of the three most recent assessments</p>

<div id="carouselRight" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        {% for assessment in right %}
        <div class="carousel-item {% if forloop.counter0 == 0 %}active{%endif%}" align="center">
            {% if program_type == "octopusg1" %}
            <img class="d-block img-fluid" src="{% url 'assessment:detail-octopusg1-field' assessment.id %}"/>
            {% elif program_type == "equidistant" %}
            <img class="d-block img-fluid" src="{% url 'assessment:detail-equidistant-field' assessment.id %}"/>
            {% endif %}
            <div class="carousel-caption text-right">
                {{assessment.date|date:"Y-m-d"}}<br/>
                {{assessment.date|date:"H:i"}}
            </div>
        </div>
        {% endfor %}
    </div>
    {% if right|length > 1 %}
    <a class="carousel-control-prev" href="#carouselRight" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselRight" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    {% endif %}
</div>

{% else %}
<div class="alert alert-info" role="alert">
    No assessments available.
</div>
{% endif %}

{% endif %}

{% endblock %}