api/urls.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views as rest_framework_views

from .views import EquidistantAssessmentList, EquidistantProgramViewSet, OctopusG1AssessmentList, \
    OctopusG1ProgramViewSet, TrainingProgramViewSet


app_name = 'api'

router = DefaultRouter()
router.register(r'program/equidistant', EquidistantProgramViewSet, base_name='EquidistantProgram')
router.register(r'program/octopusg1', OctopusG1ProgramViewSet, base_name='OctopusG1Program')
router.register(r'program/training', TrainingProgramViewSet, base_name='TrainingProgram')

urlpatterns = [
    path('v1/', include(router.urls)),
    path('v1/assessment/equidistant/', EquidistantAssessmentList.as_view()),
    path('v1/assessment/octopusg1/', OctopusG1AssessmentList.as_view()),
    path('v1/token/', rest_framework_views.obtain_auth_token, name='get_auth_token'),
]

clientconf/urls.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.urls import path, include
from django.views.decorators.cache import never_cache

from .views import index, EquidistantCreate, EquidistantUpdate, EquidistantDelete, OctopusCreate, OctopusUpdate, \
    OctopusDelete, TrainingCreate, TrainingUpdate, TrainingDelete


app_name = 'clientconf'

urlpatterns = [
    path('', never_cache(index), name='index'),
    path('equidistant/<int:pk>/', never_cache(EquidistantUpdate.as_view()), name='equidistant-update'),
    path('equidistant/create/', EquidistantCreate.as_view(), name='equidistant-create'),
    path('equidistant/delete/<int:pk>/', EquidistantDelete.as_view(), name='equidistant-delete'),
    path('octopus/<int:pk>/', never_cache(OctopusUpdate.as_view()), name='octopus-update'),
    path('octopus/create/', OctopusCreate.as_view(), name='octopus-create'),
    path('octopus/delete/<int:pk>/', OctopusDelete.as_view(), name='octopus-delete'),
    path('train/<int:pk>/', never_cache(TrainingUpdate.as_view()), name='training-update'),
    path('train/create/', TrainingCreate.as_view(), name='training-create'),
    path('train/delete/<int:pk>/', TrainingDelete.as_view(), name='training-delete'),
]

train/urls.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.urls import path

from . import views

app_name = 'train'

urlpatterns = [
    path('', views.index, name='index'),
    path('left/', views.left_eye, name='left_eye'),
    path('right/', views.right_eye, name='right_eye'),
]

vfatserver/urls.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.flatpages import views as flat_views

from main.views import CustomRegistrationView, delete_account


urlpatterns = [
    path('home/', flat_views.flatpage, {'url': '/home/'}, name='home'),
    path('main/', include('main.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/register/', CustomRegistrationView.as_view(), name='register'),
    path('accounts/delete/', delete_account, name='delete'),
    path('assessment/', include('assessment.urls')),
    path('stats/', include('stats.urls')),
    path('clientconf/', include('clientconf.urls')),
    path('train/', include('train.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

train/models.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.db import models

from assessment.models import BasicProgram
from .util import sample_coordinates
from vfatserver import consts


class TrainingProgram(BasicProgram):
    training_positions = models.IntegerField()
    random_training_color = models.BooleanField()
    reinforcement = models.BooleanField()

    def get_coordinates(self):
        return sample_coordinates(self.user, self.eye, self.training_positions, consts.training_jitter)

train/views.py
# Copyright 2019 Matthias Ring
# Machine Learning and Data Analytics Lab
# Friedrich-Alexander-University Erlangen-Nuremberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import numpy as np
import matplotlib as mpl

mpl.use('Agg')

import matplotlib.pyplot as plt

plt.style.use('seaborn')

from django.shortcuts import render

import vfatserver.util as util
from vfatserver import consts
from .util import compute_training_pdf, sample_coordinates
from assessment.util import plot_assessment
from assessment.models import EquidistantAssessment


def left_eye(request):
    return process_eye(request, 0)


def right_eye(request):
    return process_eye(request, 1)


def process_eye(request, eye):
    # get data
    positions_lon_lat_radius, pdf, _ = compute_training_pdf(request.user, eye)
    positions_xyz = util.geographic_to_cartesian(positions_lon_lat_radius)
    positions_xy = positions_xyz[:, 1:3]  # discard depth / orthographic projection

    # plot
    normalizer = mpl.colors.Normalize(vmin=np.min(np.min(0)),
                                      vmax=np.max(np.max(pdf)))
    fig, _, _ = plot_assessment(positions_xy, pdf, normalizer, 'winter_r')

    # visualize samples for verification purposes
    samples_lon_lat_radius = sample_coordinates(request.user, eye, 50, consts.training_jitter)
    samples_xyz = util.geographic_to_cartesian(samples_lon_lat_radius)
    samples_xy = samples_xyz[:, 1:3]  # discard depth / orthographic projection
    fig.axes[0].scatter(samples_xy[:, 0], samples_xy[:, 1], marker='x', facecolor='k', alpha=0.8)

    return util.fig_to_svg_response(fig)


def index(request):
    left = EquidistantAssessment.objects.filter(user=request.user, tested_eye=0).count()
    right = EquidistantAssessment.objects.filter(user=request.user, tested_eye=1).count()

    return render(request, 'train/index.html', {'left': left >= 1,
                                                'right': right >= 1})

train/templates/train/index.html
<!--
Copyright 2019 Matthias Ring
Machine Learning and Data Analytics Lab
Friedrich-Alexander-University Erlangen-Nuremberg

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->


{% extends 'base.html' %}

{% block header %}
{% include 'scripts.html' %}
{% endblock %}

{% block content %}

<h3 class="pb-3">Improvable Regions</h3>

{% if left or right %}

<p/>
    The following images show exemplary training positions (marked with an <b>x</b>)
    during a training session in the smartphone app.
    The positions are selected randomly for each training session but with
    higher probability in the more <q>blue-ish</q> regions and lower probability
    in the more <q>green-ish</q> regions.
</p>
<p>
    The colors correspond to the result of your most recent equidistant assessment. The color is
    more blue if brighter stimuli had to be presented in order to be perceivable and
    it is more green if the darker stimuli were perceived.
</p>
<p>
    The number of training positions (50 in the example below), thresholds of the training stimuli,
    and other parameters can be configured in the
    <a href="{% url 'clientconf:index' %}">app settings</a>.
</p>

<p>

</p>

<div class="row py-3">
    <div class="col-lg-6">
        <div class="mx-auto">
            <h5>Left Eye</h5>
            {% if left %}
            <div id="loading_message_1">
                <p style="font-size:x-small">Loading image...</p>
            </div>
            <img onload="imageLoaded('loading_message_1');" class="img-fluid" src="{% url 'train:left_eye'  %}"/>
            {%else%}
            <div class="alert alert-info" role="alert">
                At least one equidistant assessment is required for an analysis.
            </div>
            {%endif%}
        </div>
    </div>
    <div class="col-lg-6">
        <div class="mx-auto">
            <h5>Right Eye</h5>
            {% if right %}
            <div id="loading_message_2">
                <p style="font-size:x-small">Loading image...</p>
            </div>
            <img onload="imageLoaded('loading_message_2');" class="img-fluid" src="{% url 'train:right_eye'  %}"/>
            {%else%}
            <div class="alert alert-info" role="alert">
                At least one equidistant assessment is required for an analysis.
            </div>
            {%endif%}
        </div>
    </div>
</div>

{% else %}

<div class="alert alert-info" role="alert">
    At least one equidistant assessment is required for an analysis.
</div>

{% endif %}

{% endblock %}